#server:
#  port: 8082
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  http:
#    encoding:
#      charset: utf-8
#      enabled: true
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  config-location: classpath:config/sqlMapConfig.xml
#  type-aliases-package: com.core.parent.myshiro.entity